### ISSUE TITLE
Cannot load libyahala.so file when app runs

### ISSUE THREAD

**Issue by sunshinetpu** [wmhameed/Yahala-Messenger#1]
Here is the error log. 
                                                                   --------- beginning of crash
03-17 13:40:05.326 7263-7263/com.yahala.messenger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.yahala.messenger, PID: 7263
                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.yahala.messenger-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yahala.messenger-1/lib/arm64, /data/app/com.yahala.messenger-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libyahala.so"
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                        at java.lang.System.loadLibrary(System.java:1076)
                                                                        at com.yahala.messenger.NativeLoader.initNativeLibs(NativeLoader.java:52)
                                                                        at com.yahala.ui.ApplicationLoader.onCreate(ApplicationLoader.java:293)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4743)
                                                                        at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by a-elhusseine** [comment]
you changed app name ? package name ?

**Comment by urbanknight** [comment]
This happened only if you change the package name. 
If you want to change it you need to make some changes to the C library (Yahala-Messenger/app/jni/) and then build it again.
also you need that "libyahala.so" included in your project
